# /bin & /usr/bin
alias ls='ls -F --color'
alias ll='ls -al'
alias lh='ll -h'
alias l='ls'
alias mv='mv -i'
alias mkdir='mkdir -p'
alias find='find .'
alias ..='cd ..'

# git
alias gpush='git push origin'
alias gpull='git pull origin'
alias gst='git st'
alias gdf='git df'
alias gl='git l'
alias ga='git add'
alias gap='git add -p'
alias gci='git commit -m'
alias gco='git checkout'
alias gbr='git branch'
alias gf='git fetch'
alias gm='git merge'

# apt
alias apt-get='sudo apt-get'
alias agi='apt-get install'
alias agu='apt-get update'
alias agup='apt-get upgrade'
alias acs='apt-cache search'
alias acsh='apt-cache show'
alias agrm='apt-get remove'
